services:
    zandoo.provider_utilisateur:
        class: ZandooBundle\security\UtilisateurProvider
        arguments: ["@doctrine.orm.entity_manager","@request_stack"]
    zandoo.authentificator_utilisateur:
        class: ZandooBundle\security\UserAuthentification
        arguments: ["@security.password_encoder"] 
    zandoo.mail:
        class: ZandooBundle\Service\Mail 
#    zandoo.annonce_validator:
#        class: ZandooBundle\Validator\AnnonceValidator
#        arguments: ["@doctrine.orm.entity_manager"]
       

