# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        token:
            id:   zandoo.provider_utilisateur    
    #plaintext        
    encoders:
        Symfony\Component\Security\Core\User\User: sha512 
        ZandooBundle\Entity\Utilisateur: sha512
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        secured_area:
#            pattern: ^/admin
#            # ...
#            simple_form:
#                authenticator: zandoo.authentificator_utilisateur
#                check_path:    login_check
#                login_path:    login
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#        ZandooBundle\Entity\Utilisateur: plaintext
#
#    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#    providers:
#        smain:
#            id:   zandoo.provider_utilisateur
                 #property: username            
#        smain:
#            pattern: ^/
#            anonymous: true
#            # activate different ways to authenticate
#
#            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#            #http_basic: ~
#
#            # https://symfony.com/doc/current/security/form_login_setup.html
#            #form_login: ~
#            form_login:
#                login_path: login
#                check_path: login_check
#            logout:
#       
        main:
            pattern: ^/
            provider: token
            context: main
            anonymous: true
            simple_form:
                authenticator: zandoo.authentificator_utilisateur
                check_path: login_check
                login_path: login
                use_referer: true
                failure_path: login
            logout:
                path: /logout
                target: login           
                     
