<?php

namespace ZandooBundle\Repository;
use ZandooBundle\Entity\Annonce;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAnnonceByCritere($critere)
    {   
        $qb = $this->createQueryBuilder('a')
                ->andWhere('a.actif = 1')
                ->andWhere('a.type ='.$critere->getType())
                ->setFirstResult($critere->getOffset())
                ->setMaxResults(20);
        return  $qb->getQuery()->getResult();
    }
    
}
