<?php

namespace ZandooBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategorieByFamille(){
        $qb = $this->createQueryBuilder('c');
        $qb->addSelect('f')
            ->leftJoin('c.famille', 'f');
            //->groupBy('f.id');
            //->where($qb->expr()->eq('d.idDossier', ':idDossier'));
        //$qb->setParameter(':idDossier', $id);
        return $qb->getQuery()->getArrayResult();
    }
}
