<?php

namespace ZandooBundle\Repository;
use ZandooBundle\Entity\Utilisateur;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository implements \Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface
{
    public function loadUserByUsername($username)
    {   
        $utilisateur =  $this->finUserByPseudoOrEmail($username);
//        $password =  $this->requestStack->getCurrentRequest()->request->get("_password");
//        $utilisateur = $this->em->getRepository(Utilisateur::class)->finUserByPseudoOrEmail($username);
//        if (is_null($utilisateur)) {
//            throw new AccessDeniedHttpException(sprintf('cet utilisateur " %s " n\'existe pas.', $username));
//        }
        //dump($utilisateur);die;
        return $utilisateur;
    }
    
    public function finUserByPseudoOrEmail($username){
       $qb =  $this->createQueryBuilder('u')
                ->andWhere('u.username = :username')
                ->orWhere('u.email = :username')
                ->setParameter('username', $username);
       $ret = $qb->getQuery()->getResult();
       if($ret){
         return  $ret[0];
       }
       return $ret;
    }
}
