<?php
namespace ZandooBundle\DataFixtures;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use ZandooBundle\Entity\Famille;
use ZandooBundle\Entity\Categorie;

class FamilleCategorie implements FixtureInterface
{
	public function load(ObjectManager $manager)
    {
		$famille1 = new Famille();
		$famille1->setLibelle('maison')->setNumOrdre(1)->setActif(1);
		$manager->persist($famille1);
		
		$cat1 = new Categorie();
		$cat1->setLibelle('ameublement')->setNumOrdre(1)->setActif(1)->setFamille($famille1);
		$manager->persist($cat1);
		$cat2 = new Categorie();
		$cat2->setLibelle('electroménager')->setNumOrdre(2)->setActif(1)->setFamille($famille1);
		$manager->persist($cat2);
		$cat3 = new Categorie();
		$cat3->setLibelle('arts de la table')->setNumOrdre(3)->setActif(1)->setFamille($famille1);
		$manager->persist($cat3);
		$cat4 = new Categorie();
		$cat4->setLibelle('décoration')->setNumOrdre(4)->setActif(1)->setFamille($famille1);
		$manager->persist(cat4);
		$cat5 = new Categorie();
		$cat5->setLibelle('linge de maison')->setNumOrdre(5)->setActif(1)->setFamille($famille1);
		$manager->persist($cat5);
		$cat6 = new Categorie();
		$cat6->setLibelle('bricolage')->setNumOrdre(6)->setActif(1)->setFamille($famille1);
		$manager->persist($cat6);
		$cat7 = new Categorie();
		$cat7->setLibelle('Jardinage')->setNumOrdre(7)->setActif(1)->setFamille($famille1);
		$manager->persist($cat7);
		$cat8 = new Categorie();
		$cat8->setLibelle('Vêtements')->setNumOrdre(8)->setActif(1)->setFamille($famille1);
		$manager->persist($cat8);
		$cat9 = new Categorie();
		$cat9->setLibelle('Accessoires & Bagagerie')->setNumOrdre(9)->setActif(1)->setFamille($famille1);
		$manager->persist($cat8);
		$cat10 = new Categorie();
		$cat10->setLibelle('Montres & Bijoux')->setNumOrdre(10)->setActif(1)->setFamille($famille1);
		$manager->persist($cat9);
		$cat11 = new Categorie();
		$cat11->setLibelle('Equipement bébé')->setNumOrdre(11)->setActif(1)->setFamille($famille1);
		$manager->persist($cat10);
		$cat12 = new Categorie();
		$cat12->setLibelle('Vêtements bébé')->setNumOrdre(12)->setActif(1)->setFamille($famille1);
		$manager->persist($cat11);
		
		$famille2 = new Famille();
		$famille2->setLibelle('services')->setNumOrdre(2)->setActif(1);
		$manager->persist($famille2);
		$cat13 = new Categorie();
		$cat13->setLibelle('Prestations de services')->setNumOrdre(13)->setActif(1)->setFamille($famille2);
		$manager->persist($cat13);
		$cat14 = new Categorie();
		$cat14->setLibelle('Billetterie')->setNumOrdre(14)->setActif(1)->setFamille($famille2);
		$manager->persist($cat14);
		$cat15 = new Categorie();
		$cat15->setLibelle('Evénements')->setNumOrdre(15)->setActif(1)->setFamille($famille2);
		$manager->persist($cat15);
		$cat16 = new Categorie();
		$cat16->setLibelle('Covoiturage')->setNumOrdre(16)->setActif(1)->setFamille($famille2);
		$manager->persist($cat16);
			
		$famille3 = new Famille();
		$famille3->setLibelle('materiel professionnel')->setNumOrdre(3)->setActif(1);
		$manager->persist($famille3);
		$cat17 = new Categorie();
		$cat17->setLibelle('Matériel Agricole')->setNumOrdre(17)->setActif(1)->setFamille($famille3);
		$manager->persist($cat17);
		$cat18 = new Categorie();
		$cat18->setLibelle('Transport - Manutention')->setNumOrdre(18)->setActif(1)->setFamille($famille3);
		$manager->persist($cat18);
		$cat19 = new Categorie();
		$cat19->setLibelle('BTP - Chantier Gros-oeuvre')->setNumOrdre(19)->setActif(1)->setFamille($famille3);
		$manager->persist($cat19);
		$cat20 = new Categorie();
		$cat20->setLibelle('Outillage - Matériaux 2nd-oeuvre')->setNumOrdre(20)->setActif(1)->setFamille($famille3);
		$manager->persist($cat20);
		$cat21 = new Categorie();
		$cat21->setLibelle('Équipements Industriels')->setNumOrdre(21)->setActif(1)->setFamille($famille3);
		$manager->persist($cat21);
		$cat22 = new Categorie();
		$cat22->setLibelle('Restauration - Hôtellerie')->setNumOrdre(22)->setActif(1)->setFamille($famille3);
		$manager->persist($cat22);
		$cat23 = new Categorie();
		$cat23->setLibelle('Fournitures de Bureau')->setNumOrdre(23)->setActif(1)->setFamille($famille3);
		$manager->persist($cat23);
		$cat24 = new Categorie();
		$cat24->setLibelle('Commerces & Marchés')->setNumOrdre(24)->setActif(1)->setFamille($famille3);
		$manager->persist($cat24);
		$cat25 = new Categorie();
		$cat25->setLibelle('Matériel Médical')->setNumOrdre(25)->setActif(1)->setFamille($famille3);
		$manager->persist($cat25);
		
		$famille4 = new Famille();
		$famille4->setLibelle('multimedia')->setNumOrdre(4)->setActif(1);
		$manager->persist($famille4);
		$cat26 = new Categorie();
		$cat26->setLibelle('Informatique')->setNumOrdre(26)->setActif(1)->setFamille($famille4);
		$manager->persist($cat26);
		$cat27 = new Categorie();
		$cat27->setLibelle('Consoles & Jeux vidéo')->setNumOrdre(27)->setActif(1)->setFamille($famill4);
		$manager->persist($cat27);
		$cat28 = new Categorie();
		$cat28->setLibelle('Image & Son')->setNumOrdre(28)->setActif(1)->setFamille($famille4);
		$manager->persist($cat28);
		$cat29 = new Categorie();
		$cat29->setLibelle('Téléphonie')->setNumOrdre(29)->setActif(1)->setFamille($famille4);
		$manager->persist($cat29);		
		
		$famille5 = new Famille();
		$famille5->setLibelle('immobilier')->setNumOrdre(4)->setActif(1);
		$manager->persist($famille5);
		$cat30 = new Categorie();
		$cat30->setLibelle('Ventes immobilières')->setNumOrdre(30)->setActif(1)->setFamille($famille5);
		$manager->persist($cat30);
		$cat31 = new Categorie();
		$cat31->setLibelle('Immobilier Neufnouveau')->setNumOrdre(31)->setActif(1)->setFamille($famille5);
		$manager->persist($cat31);
		$cat32 = new Categorie();
		$cat32->setLibelle('Locations')->setNumOrdre(32)->setActif(1)->setFamille($famille5);
		$manager->persist($cat32);
		$cat33 = new Categorie();		
		$cat33->setLibelle('Colocations')->setNumOrdre(33)->setActif(1)->setFamille($famille5);
		$manager->persist($cat33);
		$cat34 = new Categorie();
		$cat34->setLibelle('Bureaux & Commerces')->setNumOrdre(34)->setActif(1)->setFamille($famille5);
		$manager->persist($cat34);
		
		$famille6 = new Famille();
		$famille6->setLibelle('emploi')->setNumOrdre(6)->setActif(1);
		$manager->persist($famille6);
		$cat35 = new Categorie();
		$cat35->setLibelle("Offres d'emploi")->setNumOrdre(35)->setActif(1)->setFamille($famille6);
		$manager->persist($cat35);
		$cat36 = new Categorie();
		$cat36->setLibelle("Offres d'emploi Cadresnouveau")->setNumOrdre(36)->setActif(1)->setFamille($famille6);
		$manager->persist($cat36);
		
		$famille7 = new Famille();
		$famille7->setLibelle('LOISIRS')->setNumOrdre(6)->setActif(1);
		$manager->persist($famille7);
		$cat37 = new Categorie();
		$cat37->setLibelle("DVD / Films")->setNumOrdre(37)->setActif(1)->setFamille($famille7);
		$manager->persist($cat37);
		$cat38 = new Categorie();
		$cat38->setLibelle("CD / Musique")->setNumOrdre(38)->setActif(1)->setFamille($famille7);
		$manager->persist($cat38);
		$cat39 = new Categorie();
		$cat39->setLibelle("Livres")->setNumOrdre(39)->setActif(1)->setFamille($famille7);
		$manager->persist($cat39);
		$cat40 = new Categorie();
		$cat40->setLibelle("Animaux")->setNumOrdre(40)->setActif(1)->setFamille($famille7);
		$manager->persist($cat40);
		$cat41 = new Categorie();
		$cat41->setLibelle("Vélos")->setNumOrdre(41)->setActif(1)->setFamille($famille7);
		$manager->persist($cat41);
		$cat42 = new Categorie();
		$cat42->setLibelle("Sports & Hobbies")->setNumOrdre(42)->setActif(1)->setFamille($famille7);
		$manager->persist($cat42);
		$cat43 = new Categorie();
		$cat43->setLibelle("Instruments de musique")->setNumOrdre(43)->setActif(1)->setFamille($famille7);
		$manager->persist($cat43);
		$cat44 = new Categorie();
		$cat44->setLibelle("Collection")->setNumOrdre(44)->setActif(1)->setFamille($famille7);
		$manager->persist($cat44);
		$cat45 = new Categorie();
		$cat45->setLibelle("Jeux & Jouets")->setNumOrdre(45)->setActif(1)->setFamille($famille7);
		$manager->persist($cat46);
		$cat46 = new Categorie();
		$cat46->setLibelle("Vins & Gastronomie")->setNumOrdre(46)->setActif(1)->setFamille($famille7);
		$manager->persist($cat46);
		
		$famille8 = new Famille();
		$famille8->setLibelle('VACANCES')->setNumOrdre(6)->setActif(1);
		$manager->persist($famille8);
		$cat47 = new Categorie();
		$cat47->setLibelle("Chambres d'hôtes")->setNumOrdre(47)->setActif(1)->setFamille($famille8);
		$manager->persist($cat47);
		$cat48 = new Categorie();
		$cat48->setLibelle("Campings")->setNumOrdre(48)->setActif(1)->setFamille($famille8);
		$manager->persist($cat48);
		$cat49 = new Categorie();
		$cat49->setLibelle("Hôtels")->setNumOrdre(49)->setActif(1)->setFamille($famille8);
		$manager->persist($cat49);
		$cat50 = new Categorie();
		$cat50->setLibelle("Hébergements insolites")->setNumOrdre(50)->setActif(1)->setFamille($famille8);
		$manager->persist($cat50);
                
                $manager->flush();
	}
}
