<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6jt1r67\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6jt1r67/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6jt1r67.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6jt1r67\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6jt1r67\appDevDebugProjectContainer(array(
    'container.build_hash' => '6jt1r67',
    'container.build_id' => '3181fb3a',
    'container.build_time' => 1529938217,
), __DIR__.\DIRECTORY_SEPARATOR.'Container6jt1r67');
