<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFw22f68\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFw22f68/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFw22f68.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFw22f68\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFw22f68\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fw22f68',
    'container.build_id' => '03e72ea8',
    'container.build_time' => 1529616225,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFw22f68');
