<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR8v0jzl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR8v0jzl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerR8v0jzl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerR8v0jzl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerR8v0jzl\appDevDebugProjectContainer(array(
    'container.build_hash' => 'R8v0jzl',
    'container.build_id' => 'b784729e',
    'container.build_time' => 1529414514,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerR8v0jzl');
