INSERT INTO famille(id,actif,libelle,num_ordre) VALUES ('1','1','EMPLOI ','1');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('1','1',"Offres d'emploi ",'1','1');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('2','1',"Offres d'emploi Cadres nouveau ",'1','2');
INSERT INTO famille(id,actif,libelle,num_ordre) VALUES ('2','1','VEHICULES ','2');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('3','1','Voitures ','2','3');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('4','1','Motos ','2','4');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('5','1','Caravaning ','2','5');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('6','1','Utilitaires ','2','6');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('7','1','Equipement Auto ','2','7');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('8','1','Equipement Moto ','2','8');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('9','1','Equipement Caravaning ','2','9');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('10','1','Nautisme ','2','10');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('11','1','Equipement Nautisme ','2','11');
INSERT INTO famille(id,actif,libelle,num_ordre) VALUES ('3','1','IMMOBILIER ','3');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('12','1','Ventes immobilières ','3','12');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('13','1','Immobilier Neuf ','3','13');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('14','1','Locations ','3','14');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('15','1','Colocations ','3','15');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('16','1','Bureaux & Commerces ','3','16');
INSERT INTO famille(id,actif,libelle,num_ordre) VALUES ('4','1','VACANCES ','4');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('17','1','Locations & Gîtes ','4','17');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('18','1',"Chambres d'hôtes ",'4','18');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('19','1','Campings ','4','19');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('20','1','Hôtels ','4','20');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('21','1','Hébergements insolites ','4','21');
INSERT INTO famille(id,actif,libelle,num_ordre) VALUES ('5','1','MULTIMEDIA ','5');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('22','1','Informatique ','5','22');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('23','1','Consoles & Jeux vidéo ','5','23');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('24','1','Image & Son ','5','24');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('25','1','Téléphonie ','5','25');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('26','1','LOISIRS ','5','26');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('27','1','DVD / Films ','5','27');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('28','1','CD / Musique ','5','28');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('29','1','Livres ','5','29');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('30','1','Animaux ','5','30');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('31','1','Vélos ','5','31');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('32','1','Sports & Hobbies ','5','32');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('33','1','Instruments de musique ','5','33');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('34','1','Collection ','5','34');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('35','1','Jeux & Jouets ','5','35');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('36','1','Vins & Gastronomie ','5','36');
INSERT INTO famille(id,actif,libelle,num_ordre) VALUES ('6','1','MATERIEL PROFESSIONNEL ','6');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('37','1','Matériel Agricole ','6','37');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('38','1','Transport - Manutention ','6','38');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('39','1','BTP - Chantier Gros-oeuvre ','6','39');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('40','1','Outillage - Matériaux 2nd-oeuvre ','6','40');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('41','1','Équipements Industriels ','6','41');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('42','1','Restauration - Hôtellerie ','6','42');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('43','1','Fournitures de Bureau ','6','43');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('44','1','Commerces & Marchés ','6','44');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('45','1','Matériel Médical ','6','45');
INSERT INTO famille(id,actif,libelle,num_ordre) VALUES ('7','1','SERVICES ','7');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('46','1','Prestations de services ','7','46');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('47','1','Billetterie ','7','47');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('48','1','Evénements ','7','48');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('49','1','Cours particuliers ','7','49');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('50','1','Covoiturage ','7','50');
INSERT INTO famille(id,actif,libelle,num_ordre) VALUES ('8','1','MAISON ','8');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('51','1','Ameublement ','8','51');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('52','1','Electroménager ','8','52');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('53','1','Arts de la table ','8','53');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('54','1','Décoration ','8','54');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('55','1','Linge de maison ','8','55');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('56','1','Bricolage ','8','56');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('57','1','Jardinage ','8','57');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('58','1','Vêtements ','8','58');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('59','1','Chaussures ','8','59');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('60','1','Accessoires & Bagagerie ','8','60');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('61','1','Montres & Bijoux ','8','61');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('62','1','Equipement bébé ','8','62');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('63','1','Vêtements bébé ','8','63');
INSERT INTO famille(id,actif,libelle,num_ordre) VALUES ('9','1','AUTRES ','9');
INSERT INTO categorie(id,actif,libelle,famille_id,num_ordre) VALUES('64','1','Autres','9','64');

INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('1','1','Bas-Uele','V001');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('2','1','Équateur ','V002');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('3','1','Haut-Katanga','V003');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('4','1','Haut-Lomami ','V004');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('5','1','Haut-Uele','V005');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('6','1','Ituri ','V006');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('7','1','Kasaï','V007');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('8','1','Kasaï-Central','V008');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('9','1','Kasaï-Oriental','V009');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('10','1','Kinshasa ','V010');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('11','1','Kongo Central','V011');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('12','1','Kwango','V012');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('13','1','Kwilu','V013');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('14','1','Lomami ','V014');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('15','1','Lualaba','V015');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('16','1','Mai-Ndombe','V016');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('17','1','Maniema','V017');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('18','1','Mongala','V018');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('19','1','Nord-Ubangi ','V019');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('20','1','North Kivu','V020');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('21','1','Sankuru','V021');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('22','1','South Kivu ','V022');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('23','1','Sud-Ubangi ','V023');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('24','1','Tanganyika','V024');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('25','1','Tshopo','V025');
INSERT INTO ville(id,actif,libelle,code_postal) VALUES ('26','1','Tshuapa','V026');

--- Alimentation motif ----
INSERT INTO motif(id,actif,libelle,date_creation) VALUES ('1','1','Fraude',NOW());
INSERT INTO motif(id,actif,libelle,date_creation) VALUES ('2','1','Doublon',NOW());
INSERT INTO motif(id,actif,libelle,date_creation) VALUES ('3','1','Mauvaise Catégorie',NOW());
INSERT INTO motif(id,actif,libelle,date_creation) VALUES ('4','1','Professionnel',NOW());
INSERT INTO motif(id,actif,libelle,date_creation) VALUES ('5','1','Déjà Vendu',NOW());
INSERT INTO motif(id,actif,libelle,date_creation) VALUES ('6','1','Discrimination',NOW());
INSERT INTO motif(id,actif,libelle,date_creation) VALUES ('7','1','Incitation à la haine',NOW());
INSERT INTO motif(id,actif,libelle,date_creation) VALUES ('8','1','Placée dans la mauvaise catégorie',NOW());
INSERT INTO motif(id,actif,libelle,date_creation) VALUES ('9','1','Autre',NOW());
--- alimentation generateur_id ---
update `annonce` set generateur_id = concat('abcdefgh',id)WHERE generateur_id is null;

UPDATE`annonce` SET prix = REPLACE(prix, ',', '');



